config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :form_elements do
    post :sort, on: :collection
  end
  resources :form_header, path: :form_elements, controller: :form_elements
  resources :form_group, path: :form_elements, controller: :form_elements
  resources :form_control, path: :form_elements, controller: :form_elements
  resources :form_feature, path: :form_elements, controller: :form_elements

  get "/search" => "search#index"

  resources :bulk_actions do
    patch :run, on: :member
    patch :revert, on: :member
  end

  resources :imports do
    resources :mappings
    resources :import_documents, only: [:show]
    patch :run, on: :member
  end

  resources :elements do
    post :sort, on: :collection
  end

  resources :bookmarks
  delete "/bookmarks", to: "bookmarks#destroy", as: :bookmarks_destroy_by_fkeys

  get "users/index"

  resources :notifications do
    put "batch", on: :collection
  end

  devise_for :users, controllers: {invitations: "devise/invitations"}, skip: [:registrations]
  as :user do
    get "/sign_in" => "devise/sessions#new" # custom path to login/sign_in
    get "/sign_up" => "devise/registrations#new", :as => "new_user_registration" # custom path to sign_up/registration
    get "users/edit" => "devise/registrations#edit", :as => "edit_user_registration"
    put "users" => "devise/registrations#update", :as => "user_registration"
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root to: "documents#index"

  # public-facing routes
  resources :documents do
    get "versions"

    resources :document_accesses, path: "access" do
      collection do
        get "import"
        post "import"

        get "destroy_all"
        post "destroy_all"
      end
    end

    resources :document_downloads, path: "downloads" do
      collection do
        get "import"
        post "import"

        get "destroy_all"
        post "destroy_all"
      end
    end

    resources :document_assets, path: "assets" do
      collection do
        get "display_attach_form"
        post "attach_files"

        get "destroy_all"
        post "destroy_all"
      end
    end

    collection do
      get "fetch"
    end
  end

  resources :document_accesses, path: "access" do
    collection do
      get "import"
      post "import"

      get "destroy_all"
      post "destroy_all"
    end
  end

  resources :document_downloads, path: "downloads" do
    collection do
      get "import"
      post "import"

      get "destroy_all"
      post "destroy_all"
    end
  end

  resources :document_assets, path: "assets" do
    collection do
      get "display_attach_form"
      post "attach_files"

      get "destroy_all"
      post "destroy_all"
    end
  end

  get "/documents/:id/ingest", to: "document_assets#display_attach_form", as: "asset_ingest"
  post "/documents/:id/ingest", to: "document_assets#attach_files"
  mount Kithe::AssetUploader.upload_endpoint(:cache) => "/direct_upload", :as => :direct_app_upload

  resources :collections, except: [:show]

  # Note "assets" is Rails reserved word for routing, oops. So we use
  # asset_files.
  resources :assets, path: "asset_files", except: [:new, :create] do
    member do
      put "convert_to_child_work"
    end
  end

  mount Qa::Engine => "/authorities"
  mount ActionCable.server => "/cable"

  authenticate :user, ->(user) { user } do
    mount Blazer::Engine, at: "blazer"
  end
end

app/models/element.rb
class Element < ApplicationRecord
  serialize :html_attributes

  # Scopes
  scope :formable, -> { where(formable: true) }
  scope :importable, -> { where(importable: true) }
  scope :exportable, -> { where(exportable: true) }
  scope :indexable, -> { where(indexable: true) }

  # Callbacks
  # @TODO: watch schema timestamp file and restart systemd services if it changes?
  # - Necessary for JSON Attr and Sidekiq to pick up new fields or changes
  # - https://unix.stackexchange.com/questions/708286/automatically-restart-a-systemd-service-when-a-file-is-modified-on-disk
  # - fswatch?
  # - cap deploy:restart

  after_save do
    File.write(Rails.root.join("tmp/schema_timestamp.txt").to_s, Time.now.to_s)
  end

  # Validations
  validates :label, :solr_field, :field_type, presence: true

  FIELD_TYPES = [
    "string",
    "text",
    "integer",
    "boolean",
    "datetime"
  ]

  # Find by solr_field shortcut
  def self.at(field)
    Element.find_by_solr_field(field)
  end

  # Element Field List (Labels as Symbols)
  def self.list
    @list ||= Element.all.map { |e| e.label.parameterize(separator: "_").to_sym }
  end

  def constantized_label
    label.parameterize(separator: "_").upcase
  end

  # Index value
  def index_value
    if index_transformation_method.present?
      index_transformation_method
    else
      solr_field
    end
  end

  # Export value
  def export_value
    if export_transformation_method.present?
      export_transformation_method
    else
      solr_field
    end
  end

  def self.label_nocase(label)
    Element.where("LOWER(label) = ?", label.to_s.tr("_", " ").downcase).first
  end

  # Class Level - Method Missing
  # ex. :title => "Title"
  def self.method_missing(m, *args, &block)
    if list.include?(m)
      label_nocase(m)
    else
      super
    end
  end

  def self.sort_elements(id_array)
    transaction do
      logger.debug { id_array.inspect }
      id_array.each_with_index do |elm_id, i|
        Element.update(elm_id, position: i)
      end
    end
  end

  def self.respond_to_missing?(method_name, include_private = false)
    label_nocase(method_name).present? || super
  end
end

app/controllers/elements_controller.rb
class ElementsController < ApplicationController
  before_action :set_element, only: %i[show edit update destroy]

  # GET /elements or /elements.json
  def index
    @pagy, @elements = pagy(Element.all.order(position: :asc), items: 100)
  end

  # GET /elements/1 or /elements/1.json
  def show
  end

  # GET /elements/new
  def new
    @element = Element.new
  end

  # GET /elements/1/edit
  def edit
  end

  # POST /elements or /elements.json
  def create
    @element = Element.new(element_params)

    respond_to do |format|
      if @element.save
        format.html { redirect_to element_url(@element), notice: "Element was successfully created." }
        format.json { render :show, status: :created, location: @element }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @element.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /elements/1 or /elements/1.json
  def update
    respond_to do |format|
      if @element.update(element_params)
        format.html { redirect_to element_url(@element), notice: "Element was successfully updated." }
        format.json { render :show, status: :ok, location: @element }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @element.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /elements/1 or /elements/1.json
  def destroy
    @element.destroy

    respond_to do |format|
      format.html { redirect_to elements_url, notice: "Element was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def sort
    Element.sort_elements(params[:id_list])
    render body: nil
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_element
    @element = Element.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def element_params
    params.require(:element).permit(:label, :solr_field, :field_definition, :field_type, :required, :repeatable, :formable, :placeholder_text, :data_entry_hint, :test_fixture_example, :controlled_vocabulary, :js_behaviors, :html_attributes, :display_only_on_persisted, :importable, :import_deliminated, :import_transformation_method, :exportable, :export_transformation_method, :indexable, :index_transformation_method, :validation_method, :position)
  end
end

app/views/elements/_form.html.erb
<%= simple_form_for(@element) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <div class="grouping">
      <h3 id="definition">Definition</h3>
      <%= f.input :label %>
      <%= f.input :solr_field %>
      <%= f.input :field_definition %>
      <%= f.input :field_type, as: :select, collection: Element::FIELD_TYPES.map { |ft| [ft, ft] }, input_html: { class: "form-control" } %>
      <%= f.input :required %>
      <%= f.input :repeatable %>
      <%= f.input :validation_method %>
    <div>

    <div class="grouping">
      <h3 id="form-settings">Form Settings</h3>
      <%= f.input :formable %>
      <%= f.input :placeholder_text %>
      <%= f.input :data_entry_hint %>
      <%= f.input :test_fixture_example %>
      <%= f.input :controlled_vocabulary %>
      <%= f.input :js_behaviors %>
      <%= f.input :html_attributes, as: :text, input_html: { 'rows' => 5 } %>
      <%= f.input :display_only_on_persisted %>
    </div>

    <div class="grouping">
      <h3 id="propagation">Propagation</h3>
      <%= f.input :importable %>
      <%= f.input :import_deliminated %>
      <%= f.input :import_transformation_method %>
      <%= f.input :exportable %>
      <%= f.input :export_transformation_method %>
      <%= f.input :indexable %>
      <%= f.input :index_transformation_method %>
    </div>
  </div>

  <div class="form-actions">
    <%= f.button :submit, class: "btn btn-primary" %>
  </div>
<% end %>

app/views/elements/edit.html.erb
<h1>Element</h1>

<%= render 'form', element: @element %>

<%= link_to 'Show', @element %> |
<%= link_to 'Back', elements_path %>

app/views/elements/index.html.erb
<%- @page_title = "GEOMG - Elements" %>

<h1 style="width:100%;">
  Elements
  <%= link_to '+ New Element', new_element_path, { class: 'btn btn-primary float-right' } %>
</h1>

<p class="alert alert-warning"><strong>Notice</strong> - This table defines the application's metadata schema fields. To add a new field to your <%= link_to 'Document', new_document_path %> form, edit your <%=link_to 'Form Elements', form_elements_path %>.</p>

<h6>
  <span class='float-left mt-3'>
    <%== pagy_info(@pagy, 'elements'.pluralize(@pagy.count)) %>
  </span>
  <span class='float-right'>
    <%== pagy_bootstrap_nav(@pagy) %>
  </span>
</h6>

<table class="table table-striped table-bordered sortable">
  <thead class="thead-dark">
    <tr>
      <th class="header">Label</th>
      <th class="header">Solr field</th>
      <th class="header">Field definition</th>
      <th class="header">Field type</th>
      <th class="header">Required</th>
      <th class="header">Repeatable</th>
      <th class="header">Reorder</th>
      <th class="header" colspan="3">Actions</th>
    </tr>
  </thead>

  <tbody>
    <% @elements.each do |element| %>
      <tr data-id="<%=element.id%>">
        <td><%= link_to element.label, element %></td>
        <td><%= element.solr_field %></td>
        <td><%= element.field_definition.present? ? link_to( element.field_definition, element.field_definition) : '' %></td>
        <td><%= element.field_type %></td>
        <td><%= element.required %></td>
        <td><%= element.repeatable %></td>
        <td class="handle" style="text-align:center">&varr;</td>
        <td><%= link_to 'Show', element %></td>
        <td><%= link_to 'Edit', edit_element_path(element) %></td>
        <td><%= link_to 'Destroy', element, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<br>

<h6>
  <span class='float-left mt-3'>
    <%== pagy_info(@pagy, 'elements'.pluralize(@pagy.count)) %>
  </span>
  <span class='float-right'>
    <%== pagy_bootstrap_nav(@pagy) %>
  </span>
</h6>

<br/>

<script>
  GEOMG.SortElements(
    $("tbody"),
    "<%= sort_elements_path %>"
  );
</script>

app/views/elements/new.html.erb
<h1>New Element</h1>

<%= render 'form', element: @element %>

<%= link_to 'Back', elements_path %>

app/views/elements/show.html.erb
<%- @page_title = "Element - #{@element.label}" %>

<h1>Element</h1>

<div class="row">
  <div class="col-9">
    <h2>
      <%= @element.label %>
      <%= link_to '~ Edit Element', edit_element_path, { class: 'btn btn-primary float-right' } %>
    </h2>

    <table class="table table-bordered">
      <thead class="thead-dark">
        <tr>
          <th class="header" style="width:300px;">Attribute</th>
          <th class="header">Value</th>
        </tr>
      </thead>
      <tr>
        <th>Label</th>
        <td><%= @element.label %></td>
      </tr>
      <tr>
        <th>Solr field</th>
        <td><%= @element.solr_field %></td>
      </tr>
      <tr>
        <th>Field definition</th>
        <td><%= @element.field_definition.present? ? link_to( @element.field_definition, @element.field_definition) : '' %></td>
      </tr>
      <tr>
        <th>Field type</th>
        <td><%= @element.field_type %></td>
      </tr>
      <tr>
        <th>Required</th>
        <td><%= @element.required %></td>
      </tr>
      <tr>
        <th>Repeatable</th>
        <td><%= @element.repeatable %></td>
      </tr>
      <tr>
        <th>Formable</th>
        <td><%= @element.formable %></td>
      </tr>
      <tr>
        <th>Placeholder text</th>
        <td><%= @element.placeholder_text %></td>
      </tr>
      <tr>
        <th>Data entry hint</th>
        <td><%= @element.data_entry_hint %></td>
      </tr>
      <tr>
        <th>Test fixture example</th>
        <td><%= @element.test_fixture_example %></td>
      </tr>
      <tr>
        <th>Controlled vocabulary</th>
        <td><%= @element.controlled_vocabulary %></td>
      </tr>
      <tr>
        <th>JS Behavior</th>
        <td><%= @element.js_behaviors %></td>
      </tr>
      <tr>
        <th>HTML attributes</th>
        <td><%= @element.html_attributes %></td>
      </tr>
      <tr>
        <th>Display only on persisted?</th>
        <td><%= @element.display_only_on_persisted %></td>
      </tr>
      <tr>
        <th>Importable?</th>
        <td><%= @element.importable %></td>
      </tr>
      <tr>
        <th>Import deliminated?</th>
        <td><%= @element.import_deliminated %></td>
      </tr>
      <tr>
        <th>Import transformation method</th>
        <td><%= @element.import_transformation_method %></td>
      </tr>
      <tr>
        <th>Exportable?</th>
        <td><%= @element.exportable %></td>
      </tr>
      <tr>
        <th>Export transformation method</th>
        <td><%= @element.export_transformation_method %></td>
      </tr>
      <tr>
        <th>Indexable?</th>
        <td><%= @element.indexable %></td>
      </tr>
      <tr>
        <th>Index transformation method</th>
        <td><%= @element.index_transformation_method %></td>
      </tr>
      <tr>
        <th>Validation method</th>
        <td><%= @element.validation_method %></td>
      </tr>
    </table>
  </div>

  <div class="col-3">
    <h3><%= link_to "Elements", elements_path %></h3>
    <%- @elements = Element.all %>
    <ul>
      <%- @elements.each do |elm| %>
        <li><%= link_to_unless_current(elm.label, elm) %></li>
      <%- end %>
    </ul>
  </div>
</div>
<%= link_to 'Edit', edit_element_path(@element) %> |
<%= link_to 'Back', elements_path %>