config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :form_elements do
    post :sort, on: :collection
  end
  resources :form_header, path: :form_elements, controller: :form_elements
  resources :form_group, path: :form_elements, controller: :form_elements
  resources :form_control, path: :form_elements, controller: :form_elements
  resources :form_feature, path: :form_elements, controller: :form_elements

  get "/search" => "search#index"

  resources :bulk_actions do
    patch :run, on: :member
    patch :revert, on: :member
  end

  resources :imports do
    resources :mappings
    resources :import_documents, only: [:show]
    patch :run, on: :member
  end

  resources :elements do
    post :sort, on: :collection
  end

  resources :bookmarks
  delete "/bookmarks", to: "bookmarks#destroy", as: :bookmarks_destroy_by_fkeys

  get "users/index"

  resources :notifications do
    put "batch", on: :collection
  end

  devise_for :users, controllers: {invitations: "devise/invitations"}, skip: [:registrations]
  as :user do
    get "/sign_in" => "devise/sessions#new" # custom path to login/sign_in
    get "/sign_up" => "devise/registrations#new", :as => "new_user_registration" # custom path to sign_up/registration
    get "users/edit" => "devise/registrations#edit", :as => "edit_user_registration"
    put "users" => "devise/registrations#update", :as => "user_registration"
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root to: "documents#index"

  # public-facing routes
  resources :documents do
    get "versions"

    resources :document_accesses, path: "access" do
      collection do
        get "import"
        post "import"

        get "destroy_all"
        post "destroy_all"
      end
    end

    resources :document_downloads, path: "downloads" do
      collection do
        get "import"
        post "import"

        get "destroy_all"
        post "destroy_all"
      end
    end

    resources :document_assets, path: "assets" do
      collection do
        get "display_attach_form"
        post "attach_files"

        get "destroy_all"
        post "destroy_all"
      end
    end

    collection do
      get "fetch"
    end
  end

  resources :document_accesses, path: "access" do
    collection do
      get "import"
      post "import"

      get "destroy_all"
      post "destroy_all"
    end
  end

  resources :document_downloads, path: "downloads" do
    collection do
      get "import"
      post "import"

      get "destroy_all"
      post "destroy_all"
    end
  end

  resources :document_assets, path: "assets" do
    collection do
      get "display_attach_form"
      post "attach_files"

      get "destroy_all"
      post "destroy_all"
    end
  end

  get "/documents/:id/ingest", to: "document_assets#display_attach_form", as: "asset_ingest"
  post "/documents/:id/ingest", to: "document_assets#attach_files"
  mount Kithe::AssetUploader.upload_endpoint(:cache) => "/direct_upload", :as => :direct_app_upload

  resources :collections, except: [:show]

  # Note "assets" is Rails reserved word for routing, oops. So we use
  # asset_files.
  resources :assets, path: "asset_files", except: [:new, :create] do
    member do
      put "convert_to_child_work"
    end
  end

  mount Qa::Engine => "/authorities"
  mount ActionCable.server => "/cable"

  authenticate :user, ->(user) { user } do
    mount Blazer::Engine, at: "blazer"
  end
end

app/models/document_download.rb
# frozen_string_literal: true

# DocumentDownload
class DocumentDownload < ApplicationRecord
  belongs_to :document, inverse_of: :document_downloads, foreign_key: :friendlier_id, primary_key: :friendlier_id
  after_save :reindex_document

  # Validations
  validates :label, :value, presence: true

  def self.import(file)
    logger.debug("CSV Import")
    CSV.foreach(file.path, headers: true) do |row|
      logger.debug("CSV Row: #{row.to_hash}")
      document_download = DocumentDownload.find_or_initialize_by(friendlier_id: row[0], label: row[1], value: row[2])
      document_download.update(row.to_hash)
    end
  end

  def self.destroy_all(file)
    logger.debug("CSV Destroy")
    CSV.foreach(file.path, headers: true) do |row|
      logger.debug("CSV Row: #{row.to_hash}")
      DocumentDownload.destroy_by(id: row[0], friendlier_id: row[1])
    end
  end

  def to_csv
    attributes.values
  end

  def reindex_document
    document.save
  end
end

app/controllers/document_downloads_controller.rb
# frozen_string_literal: true

# DocumentDownloadsController
class DocumentDownloadsController < ApplicationController
  before_action :set_document
  before_action :set_document_download, only: %i[show edit update destroy]

  # GET /document_downloads or /document_downloads.json
  def index
    @document_downloads = DocumentDownload.all
    if params[:document_id]
      @document_downloads = DocumentDownload.where(friendlier_id: @document.friendlier_id).order(position: :asc)
    else
      @pagy, @document_downloads = pagy(DocumentDownload.all.order(friendlier_id: :asc, updated_at: :desc), items: 20)
    end
  end

  # GET /document_downloads/1 or /document_downloads/1.json
  def show
  end

  # GET /document_downloads/new
  def new
    @document_download = DocumentDownload.new
  end

  # GET /document_downloads/1/edit
  def edit
  end

  # POST /document_downloads or /document_downloads.json
  def create
    @document_download = DocumentDownload.new(document_download_params)

    logger.debug("DD Params: #{DocumentDownload.new(document_download_params).inspect}")
    logger.debug("Document DOWNLOAD: #{@document_download.inspect}")

    respond_to do |format|
      if @document_download.save
        format.html do
          redirect_to document_document_downloads_path(@document_download.document), notice: "Document download was successfully created."
        end
        format.json { render :show, status: :created, location: @document_download }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @document_download.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /document_downloads/1 or /document_downloads/1.json
  def update
    respond_to do |format|
      if @document_download.update(document_download_params)
        format.html do
          redirect_to document_document_downloads_path(@document_download.document), notice: "Document download was successfully updated."
        end
        format.json { render :show, status: :ok, location: @document_download }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @document_download.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /document_downloads/1 or /document_downloads/1.json
  def destroy
    @document_download.destroy

    respond_to do |format|
      format.html { redirect_to document_downloads_url, notice: "Document download was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def destroy_all
    logger.debug("Destroy Downloads")
    return unless params.dig(:document_download, :downloads, :file)

    respond_to do |format|
      if DocumentDownload.destroy_all(params.dig(:document_download, :downloads, :file))
        format.html { redirect_to document_downloads_path, notice: "Download Links were created destroyed." }
      else
        format.html { redirect_to document_downloads_path, notice: "Download Links could not be destroyed." }
      end
    rescue => e
      format.html { redirect_to document_downloads_path, notice: "Download Links could not be destroyed. #{e}" }
    end
  end

  # GET   /documents/#id/downloads/import
  # POST  /documents/#id/downloads/import
  def import
    logger.debug("Import Downloads")
    return unless params.dig(:document_download, :downloads, :file)

    respond_to do |format|
      if DocumentDownload.import(params.dig(:document_download, :downloads, :file))
        format.html { redirect_to document_downloads_path, notice: "Download Links were created successfully." }
      else
        format.html { redirect_to document_downloads_path, notice: "Download Links could not be created." }
      end
    rescue => e
      format.html { redirect_to document_downloads_path, notice: "Download Links could not be created. #{e}" }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_document
    return unless params[:document_id] # If not nested

    @document = Document.includes(:leaf_representative).find_by!(friendlier_id: params[:document_id])
  end

  def set_document_download
    @document_download = DocumentDownload.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def document_download_params
    params.require(:document_download).permit(:friendlier_id, :label, :value, :position)
  end
end

app/views/document_downloads/_form.html.erb
<%= simple_form_for(@document_download) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :friendlier_id, input_html: { value: @document.friendlier_id, readonly: true } %>
    <%= f.input :label, autofocus: true %>
    <%= f.input :value, label: 'Download URL' %>
  </div>

  <div class="form-actions">
    <%= f.button :submit, 'Create Download URL', {class: 'btn btn-primary'} %>
  </div>
<% end %>

app/views/document_downloads/destroy_all.html.erb
<p id="notice"><%= notice %></p>

<h1 style="width:100%; border-bottom:dotted;" class="mb-4">
  Document &middot; Destroy Download Links
  <% if params[:document_id] %>
    <%= link_to '+ New Download Link', new_document_document_download_path(@document), { class: 'btn btn-primary float-right' } %>
  <% end %>
</h1>

<div class="row">
  <div class="col-6">
    <% if params[:document_id] %>
      <h2 class='h3'><%= @document.title %></h2>
    <% else %>
      <h2 class='h3'>Destroy Multiple Download Links</h2>
    <% end %>

    <p class="alert alert-danger" role="alert">
      <strong>Warning:</strong> All matching Download Links will be destroyed. There is <strong>NO UNDO</strong> here.
    </p>
    <h3 class='h4'>Upload a CSV File</h3>

    <%= simple_form_for DocumentDownload.new, url: destroy_all_document_downloads_path, method: :post, multipart: true do |f| %>
      <div class="form-group">
        <div class="form-inputs">
          <%= f.simple_fields_for :downloads do |download_fields| %>
            <%= download_fields.input :file, as: :file, input_html: {} %>
          <%- end %>
        </div>

        <div class="form-actions">
          <%= submit_tag "- Destroy All", {class: 'btn btn-danger'} %>
        </div>
      </div>
    <% end %>
  </div>
  <div class="col-6">
    <h4>Example CSV File</h4>
    <table class="table table-bordered">
      <thead>
        <tr>
          <th>id</th>
          <th>friendlier_id</th>
        </tr>
      </thead>
      <tbody>
        <tr>
          <td>1</td>
          <td>a35bf4a4-e3ef-483e-98c4-7ea1b04b0f0d</td>
        </tr>
        <tr>
          <td>207</td>
          <td>a35bf4a4-e3ef-483e-98c4-7ea1b04b0f0d</td>
        </tr>
        <tr>
          <td>...</td>
          <td>...</td>
        </tr>
      </tbody>
    </table>

    <h5>CSV File Column Definitions</h5>
    <dl>
      <dt>id</dt>
      <dd>The database table row identifier</dd>
      <dt>friendlier_id</dt>
      <dd>The associated GEOMG document's friendlier id</dd>
    </dl>
  </div>
</div>

app/views/document_downloads/edit.html.erb
<h1>Editing Document Download</h1>

<%= render 'form', document_download: @document_download %>

<%= link_to 'Show', @document_download %> |
<%= link_to 'Back', document_downloads_path %>

app/views/document_downloads/import.html.erb
<p id="notice"><%= notice %></p>

<h1 style="width:100%; border-bottom:dotted;" class="mb-4">
  Document &middot; Download Links
  <% if params[:document_id] %>
    <%= link_to '+ New Download Link', new_document_document_download_path(@document), { class: 'btn btn-primary float-right' } %>
  <% end %>
</h1>

<div class="row">
  <div class="col-6">
    <% if params[:document_id] %>
      <h2 class='h3'><%= @document.title %></h2>
    <% else %>
      <h2 class='h3'>Import for Multiple Documents</h2>
    <% end %>

    <p class="alert alert-info" role="alert">
      <strong>Note:</strong> New Download Links will be created. Existing Download Links will be updated per the CSV file.
    </p>

    <h3 class="h4">Upload a CSV File</h3>
    <%= simple_form_for DocumentDownload.new, url: import_document_downloads_path, method: :post, multipart: true do |f| %>
      <div class="form-inputs">
        <%= f.simple_fields_for :downloads do |download_fields| %>
          <%= download_fields.input :file, as: :file, input_html: {} %>
        <%- end %>
      </div>

      <div class="form-actions">
        <%= submit_tag "+ Import CSV", {class: 'btn btn-primary'} %>
      </div>
    <% end %>
  </div>
  <div class="col-6">
    <h4>Example CSV File</h4>
    <table class="table table-bordered">
      <thead>
        <tr>
          <th>friendlier_id</th>
          <th>label</th>
          <th>value</th>
        </tr>
      </thead>
      <tbody>
        <tr>
          <td>00add5b8-a7b1-42d4-b4de-ca99716a5096</td>
          <td>GeoTIFF</td>
          <td>https://s3.amazonaws.com/holc/tiles/WI/Madison/1937/rectified.zip</td>
        </tr>
        <tr>
          <td>00add5b8-a7b1-42d4-b4de-ca99716a5096</td>
          <td>JPEG</td>
          <td>https://s3.amazonaws.com/holc/tiles/WI/Madison/1937/holc-scan.jpg</td>
        </tr>
        <tr>
          <td>...</td>
          <td>...</td>
          <td>...</td>
        </tr>
      </tbody>
    </table>

    <h5>CSV File Column Definitions</h5>
    <dl>
      <dt>friendlier_id</dt>
      <dd>The associated GEOMG document's friendlier id</dd>
      <dt>label</dt>
      <dd>The label for the Download link</dd>
      <dt>value</dt>
      <dd>The URL for the Download link</dd>
    </dl>
  </div>
</div>

app/views/document_downloads/index.html.erb
<%- @page_title = "GEOMG - Document - Download Links" %>

<h1 style="width:100%;">
  Document &middot; Download Links

  <% if params[:document_id] %>
    <%= link_to '+ Import CSV', import_document_document_downloads_path(@document), { class: 'btn btn-primary float-right' } %>

    <%= link_to '+ New Download URL', new_document_document_download_path(@document), { class: 'btn btn-primary float-right mr-2' } %>
  <% else %>
    <%= link_to '- Delete CSV', destroy_all_document_downloads_path(), { class: 'btn btn-danger float-right' } %>
    <%= link_to '+ Import CSV', import_document_downloads_path(), { class: 'btn btn-primary float-right mr-4' } %>
  <% end %>
</h1>
<% if params[:document_id] %>
  <h2 class='h3'>
    <%= link_to(@document.title, document_path(@document)) %>
    &middot;
    <%= @document_downloads.count %> downloads
  </h2>
<% else %>
  <h2 class='h3'>Download Links</h2>
<% end %>

<% if @pagy %>
<h6>
  <span class='float-left mt-3'>
    <%== pagy_info(@pagy, 'downloads'.pluralize(@pagy.count)) %>
  </span>
  <span class='float-right'>
    <%== pagy_bootstrap_nav(@pagy) %>
  </span>
</h6>
<% end %>

<table class="table table-striped table-bordered sortable">
  <thead class="thead-dark">
    <tr>
      <th class="header" colspan="2">Actions</th>
      <th class="header">Layer Slug</th>
      <th class="header">Download Label</th>
      <th class="header">Download URL</th>
    </tr>
  </thead>

  <tbody>
    <% @document_downloads.each do |document_download| %>
      <tr>
        <td><%= link_to 'Edit', edit_document_document_download_path(document_download.document, document_download) %></td>
        <td><%= link_to 'Destroy', document_document_download_path(document_download.document, document_download), method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <td><%= link_to document_download.friendlier_id, document_path(document_download.document) %></td>
        <td><%= document_download.label %></td>
        <td><%= link_to document_download.value %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<% if @pagy %>
<h6>
  <span class='float-left mt-3'>
    <%== pagy_info(@pagy, 'downloads'.pluralize(@pagy.count)) %>
  </span>
  <span class='float-right'>
    <%== pagy_bootstrap_nav(@pagy) %>
  </span>
</h6>
<% end %>

<br>

app/views/document_downloads/new.html.erb
<h1>New Document Download</h1>

<%= render 'form', document_download: @document_download %>

<%= link_to 'Back', document_downloads_path %>

app/views/document_downloads/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Friendlier:</strong>
  <%= @document_download.friendlier_id %>
</p>

<p>
  <strong>Label:</strong>
  <%= @document_download.label %>
</p>

<p>
  <strong>Value:</strong>
  <%= @document_download.value %>
</p>

<p>
  <strong>Position:</strong>
  <%= @document_download.position %>
</p>

<%= link_to 'Edit', edit_document_download_path(@document_download) %> |
<%= link_to 'Back', document_downloads_path %>