config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :form_elements do
    post :sort, on: :collection
  end
  resources :form_header, path: :form_elements, controller: :form_elements
  resources :form_group, path: :form_elements, controller: :form_elements
  resources :form_control, path: :form_elements, controller: :form_elements
  resources :form_feature, path: :form_elements, controller: :form_elements

  get "/search" => "search#index"

  resources :bulk_actions do
    patch :run, on: :member
    patch :revert, on: :member
  end

  resources :imports do
    resources :mappings
    resources :import_documents, only: [:show]
    patch :run, on: :member
  end

  resources :elements do
    post :sort, on: :collection
  end

  resources :bookmarks
  delete "/bookmarks", to: "bookmarks#destroy", as: :bookmarks_destroy_by_fkeys

  get "users/index"

  resources :notifications do
    put "batch", on: :collection
  end

  devise_for :users, controllers: {invitations: "devise/invitations"}, skip: [:registrations]
  as :user do
    get "/sign_in" => "devise/sessions#new" # custom path to login/sign_in
    get "/sign_up" => "devise/registrations#new", :as => "new_user_registration" # custom path to sign_up/registration
    get "users/edit" => "devise/registrations#edit", :as => "edit_user_registration"
    put "users" => "devise/registrations#update", :as => "user_registration"
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root to: "documents#index"

  # public-facing routes
  resources :documents do
    get "versions"

    resources :document_accesses, path: "access" do
      collection do
        get "import"
        post "import"

        get "destroy_all"
        post "destroy_all"
      end
    end

    resources :document_downloads, path: "downloads" do
      collection do
        get "import"
        post "import"

        get "destroy_all"
        post "destroy_all"
      end
    end

    resources :document_assets, path: "assets" do
      collection do
        get "display_attach_form"
        post "attach_files"

        get "destroy_all"
        post "destroy_all"
      end
    end

    collection do
      get "fetch"
    end
  end

  resources :document_accesses, path: "access" do
    collection do
      get "import"
      post "import"

      get "destroy_all"
      post "destroy_all"
    end
  end

  resources :document_downloads, path: "downloads" do
    collection do
      get "import"
      post "import"

      get "destroy_all"
      post "destroy_all"
    end
  end

  resources :document_assets, path: "assets" do
    collection do
      get "display_attach_form"
      post "attach_files"

      get "destroy_all"
      post "destroy_all"
    end
  end

  get "/documents/:id/ingest", to: "document_assets#display_attach_form", as: "asset_ingest"
  post "/documents/:id/ingest", to: "document_assets#attach_files"
  mount Kithe::AssetUploader.upload_endpoint(:cache) => "/direct_upload", :as => :direct_app_upload

  resources :collections, except: [:show]

  # Note "assets" is Rails reserved word for routing, oops. So we use
  # asset_files.
  resources :assets, path: "asset_files", except: [:new, :create] do
    member do
      put "convert_to_child_work"
    end
  end

  mount Qa::Engine => "/authorities"
  mount ActionCable.server => "/cable"

  authenticate :user, ->(user) { user } do
    mount Blazer::Engine, at: "blazer"
  end
end

app/views/shared/_flash_messages.html.erb
<% flash.each do |key, value| %>
  <div class="<%= flash_class(key) %>">
    <%= value %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<!-- Footer -->
<footer class="page-footer font-small pt-4 bg-secondary text-white">

  <!-- Footer Links -->
  <div class="container-fluid text-center text-md-left">

    <!-- Grid row -->
    <div class="row">
      <div class="col-12 ">
        <h4 style="margin-bottom:1.5rem;">
          GEOMG // GeoBlacklight Metadata Toolkit
        </h4>
      </div>

      <!-- Grid column -->
      <div class="col-md-6 mt-md-0 mt-3">

        <!-- Content -->

        <p style="background-color:#FFF; padding:1rem; padding-bottom:0;"><%= image_tag('btaa-logo.jpg', height: '120px') %></p>

      </div>
      <!-- Grid column -->

      <hr class="clearfix w-100 d-md-none pb-3">

      <!-- Grid column -->
      <div class="col-md-3 mb-md-0 mb-3">

        <!-- Links -->
        <h5>Resources</h5>

        <ul class="list-unstyled">
          <li>
            <a href="https://opengeometadata.org" class="text-white">OpenGeoMetadata</a>
          </li>
        </ul>

      </div>
      <!-- Grid column -->
      <div class="col-md-3 mb-md-0 mb-3">
        <!-- Links -->
        <h5>Help</h5>
        <ul class="list-unstyled">
          <li>
            <a href="#" class="text-white">Contact Support</a>
          </li>
        </ul>
      </div>

      <div class="col-12">
        <p>
          <small>© <%=Time.now.year%> Big Ten Academic Alliance</small>
        </p>
      <div>

    </div>
    <!-- Grid row -->

  </div>
  <!-- Footer Links -->

</footer>

app/views/shared/_js_behaviors.html.erb
<script>
  $(function () {
    if ($('[data-toggle="tooltip"]').length > 0) {
      //$('[data-toggle="tooltip"]').tooltip();
    }
  });

  // Date Range picker
  $('#date-range').on('change', function(event){
    GEOMG.DateRangeSelect();

    if ($('#compare').length > 0) {
      GEOMG.CompareRangeSelect();
    }
  });

  // Compare Range checkbox toggle
  $("input#compare").on('change', function(event){
    GEOMG.DisplayCompareDateRange();
    GEOMG.CompareRangeSelect();
    GEOMG.ToggleCompare();
  });

  // Compare Range picker
  $('#compare-options').on('change', function(event){
    GEOMG.CompareRangeSelect();
  });

  // Bootstrap DateRangePicker
  $('input[name="daterange"]').daterangepicker({
    autoUpdateInput: false,
    locale: { cancelLabel: 'Clear' }
    });

  $('input[name="daterange"]').on('apply.daterangepicker', function(ev, picker) {
      $(this).val(picker.startDate.format('MM/DD/YYYY') + ' - ' + picker.endDate.format('MM/DD/YYYY'));

  });

  $('input[name="daterange"]').on('cancel.daterangepicker', function(ev, picker) {
      $(this).val('');
  });

  $(document).on('ready turbolinks:load', function() {
    GEOMG.DisableIfPersisted();
  });
</script>

<script type="module">
  import {Uppy, Dashboard, XHRUpload} from "https://releases.transloadit.com/uppy/v3.6.1/uppy.min.mjs"

  if (document.getElementsByClassName('uppy-dashboard-container').length > 0) {

    var closest = function(el, fn) {
      return el && (fn(el) ? el : closest(el.parentNode, fn));
    }
    
    var container = document.getElementsByClassName('uppy-dashboard-container')[0];
    var containerForm = closest(container, function(el) { return el.tagName.toLowerCase() == "form" });
    var cachedFileTableEl = containerForm.querySelector("*[data-toggle='cached-files-table']");
    var browseEverythingButton = containerForm.querySelector('*[data-toggle="kithe-browse-everything"]');
    var submitButton = containerForm.querySelector("*[data-toggle='kithe-upload-submit']");

    var uppy = new Uppy()
      .use(Dashboard, {
        inline: true,
        target: '.uppy-dashboard-container'
      })
      .use(XHRUpload, { 
        endpoint: '/direct_upload',
        fieldName: 'file'
      })

    // Turns a number of bytes into human readable eg "12GB"
    // https://stackoverflow.com/a/38897674
    var fileSizeSI = function(size) {
      var e = (Math.log(size) / Math.log(1e3)) | 0;
      return +(size / Math.pow(1e3, e)).toFixed(1) + ' ' + ('kMGTPEZY'[e - 1] || '') + 'B';
    }

    // Returns the <input type="hidden"> representing a direct-uploaded
    // file, to be sent to controller for attachment. Value will be a JSON
    // serialization of the hash describing the uploaded-to-cache file,
    // to be sent to the controller.
    var makeHiddenFieldForCachedFile = function(shrineHash) {
      var hidden = document.createElement("input");
      hidden.setAttribute("type", "hidden");
      hidden.setAttribute("name", "cached_files[]");
      hidden.setAttribute("value", JSON.stringify(shrineHash));

      return hidden;
    }

    // create a DOM element for a table row that will be the list of succesfully
    // direct uploaded files, including hidden inputs to be submitted with form,
    // and a remove button to remove it from list.
    //
    // With just browser API, yeah, it's a bit ugly code.
    var makeCachedFileRow = function(shrineHash) {
      var row = document.createElement("tr");

      var firstCell = row.appendChild(document.createElement("td"));
      firstCell.appendChild(makeHiddenFieldForCachedFile(shrineHash));
      firstCell.appendChild(document.createTextNode(shrineHash.metadata.filename));

      if (shrineHash.metadata.size) {
        var size = fileSizeSI(shrineHash.metadata.size);
      } else {
        var size = "";
      }

      row.appendChild(document.createElement("td")).innerText = size;

      // Storage type control, put in params keyed by file ID
      row.appendChild(document.createElement("td")).innerHTML =
        "<select name='storage_type_for[" + shrineHash.id + "]' class='form-control derivative-storage-type'>" +
          "<option>public</option><option>restricted</option>" +
        "</select>";

      row.appendChild(document.createElement("td")).innerHTML =
        "<button type='button' data-cached-file-remove='true' class='btn btn-link' aria-label='Remove' title='Remove'>" +
          "<i class='fa fa-times-circle' style='font-size: 180%' aria-hidden='true'></i>" +
        "</button>";

      return row;
    }

    // Upload Success
    // When a file is fully direct uploaded by uppy, we remove it from uppy dashboard,
    // and instead list it in our list of files to be attached on form submit.
    uppy.on("upload-success", function(file, response) {
      var shrineHash = response.body;

      // add the file to our list that will be submitted with form
      cachedFileTableEl.appendChild(makeCachedFileRow(shrineHash));

      // And remove from uppy dashboard, we're treating that just as the in-progress
      // list. This means we won't get a `complete` callback though. :(
      uppy.removeFile(file.id);
    });

    // Upload Complete
    uppy.on('complete', (result) => {
      console.log('Upload complete! We’ve uploaded these files:', result.successful)
    })
  }
</script>

app/views/shared/_navbar.html.erb
<nav class="navbar fixed-top navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="<%=root_url%>">
    <strong>G&middot;E&middot;O&middot;M&middot;G</strong>
  </a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <%= form_tag(documents_path, { method: :get, class: "form-inline my-2 my-lg-0" }) do %>

    <div class="input-group">
      <input name="q" class="form-control" type="search" placeholder="Search documents" aria-label="Search" value="<%= params[:q] ? params[:q] : ''%>">
      <%- if params[:f].present? %>
        <%= params_as_hidden_fields(
            params
            .to_hash
            .with_indifferent_access
            .except(:q, :controller, :action, :commit)
          ) %>
      <% end %>

      <div class="input-group-append">
        <button class="btn btn-outline-secondary my-2 my-sm-0" type="submit">Search</button>
        <button type="button" class="btn btn-outline-secondary dropdown-toggle dropdown-toggle-split" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          <span class="sr-only">Toggle Dropdown</span>
        </button>
        <div class="dropdown-menu">
          <%= link_to "Advanced", search_path, { class: 'dropdown-item' } %>
        </div>
      </div>
    </div>
  <% end %>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav flex-row ml-md-auto d-none d-md-flex">
      <% if user_signed_in? %>
        <li class="nav-item">
          <%= link_to notifications_url, { class: 'nav-link' } do %>
            <%= "Notifications #{notifications_badge}".html_safe %>
          <% end %>
        </li>
      <% end %>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Admin Tools
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <%= link_to "Documents", documents_path, {class: 'dropdown-item'} %>
          <%= link_to "Imports", imports_path, {class: 'dropdown-item'} %>
          <%= link_to "Bulk Actions", bulk_actions_path, {class: 'dropdown-item'} %>
          <div class="dropdown-divider"></div>
          <%= link_to "Access Links", document_accesses_path, {class: 'dropdown-item'} %>
          <%= link_to "Download Links", document_downloads_path, {class: 'dropdown-item'} %>
          <div class="dropdown-divider"></div>
          <%= link_to "Blazer", '/blazer', {class: 'dropdown-item', data: { turbolinks: false }} %>
          <div class="dropdown-divider"></div>
          <%= link_to "Elements", elements_path, {class: 'dropdown-item', data: { turbolinks: false }} %>
          <%= link_to "Form Elements", form_elements_path, {class: 'dropdown-item', data: { turbolinks: false }} %>
          <div class="dropdown-divider"></div>
          <%= link_to "Users", users_index_path, {class: 'dropdown-item'} %>
        </div>
      <li class="nav-item">
        <%= link_to "Bookmarks", bookmarks_path, {class: 'nav-link'} if current_user %>
      </li>
      <% if user_signed_in? %>
        <li class="nav-item">
          <%= link_to(current_user.email, edit_user_registration_path, {class: 'nav-link'}) %>
        </li>
        <li class="nav-item">
          <%= link_to "Sign out", destroy_user_session_path, { :method => :delete, class: 'nav-link'} %>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to('Sign in', new_user_session_path, {class: 'nav-link'}) %>
        </li>
      <% end %>
    </ul>
  </div>
</nav>

app/views/shared/_navbar_blazer.html.erb
<nav class="navbar fixed-top navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="/">
    <strong>G&middot;E&middot;O&middot;M&middot;G</strong>
  </a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <%= form_tag('/documents', { method: :get, class: "form-inline my-2 my-lg-0" }) do %>

    <div class="input-group">
      <input name="q" class="form-control" type="search" placeholder="Search documents" aria-label="Search" value="<%= params[:q] ? params[:q] : ''%>">
      <%- if params[:f].present? %>
        <%= params_as_hidden_fields(
            params
            .to_hash
            .with_indifferent_access
            .except(:q, :controller, :action, :commit)
          ) %>
      <% end %>

      <div class="input-group-append">
        <button class="btn btn-outline-secondary my-2 my-sm-0" type="submit">Search</button>
        <button type="button" class="btn btn-outline-secondary dropdown-toggle dropdown-toggle-split" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          <span class="sr-only">Toggle Dropdown</span>
        </button>
        <div class="dropdown-menu">
          <%= link_to "Advanced", '/search', { class: 'dropdown-item' } %>
        </div>
      </div>
    </div>
  <% end %>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="navbar-nav flex-row ml-md-auto d-none d-md-flex">
        <li class="nav-item">
          <%= link_to "Blazer &middot; Business Intelligence Tools".html_safe, '/blazer', {class: 'nav-link'} if current_user %>
        </li>
      </ul>
    </div>
  </div>
</nav>

app/views/shared/_schema_timestamp.html.erb
<%- 
  schema_warning = false
  if File.exist?(Rails.root.join("tmp/schema_timestamp.txt").to_s)
    current_timestamp = File.read(Rails.root.join("tmp/schema_timestamp.txt").to_s)
    if current_timestamp != GEOMG_SCHEMA_TIMESTAMP
      schema_warning = true
    end
  end
%>

<%- if schema_warning %>
  <div class="alert alert-danger" role="alert">
    <strong>Warning:</strong> The project's metadata schema has changed. You need to restart the application server.
  </div>
<%- end %>

app/views/shared/_toast.html.erb
<!-- Toast -->
<div class="toast" role="alert" aria-live="assertive" aria-atomic="true" style="position:relative; top:0; right:0;" data-delay="5000">
  <div class="toast-header">
    <strong class="mr-auto">GEOMG</strong>
    <small class="text-muted">just now</small>
    <button type="button" class="ml-2 mb-1 close" data-dismiss="toast" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
  <div class="toast-body">
    <%= toast %>
  </div>
</div>