config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :form_elements do
    post :sort, on: :collection
  end
  resources :form_header, path: :form_elements, controller: :form_elements
  resources :form_group, path: :form_elements, controller: :form_elements
  resources :form_control, path: :form_elements, controller: :form_elements
  resources :form_feature, path: :form_elements, controller: :form_elements

  get "/search" => "search#index"

  resources :bulk_actions do
    patch :run, on: :member
    patch :revert, on: :member
  end

  resources :imports do
    resources :mappings
    resources :import_documents, only: [:show]
    patch :run, on: :member
  end

  resources :elements do
    post :sort, on: :collection
  end

  resources :bookmarks
  delete "/bookmarks", to: "bookmarks#destroy", as: :bookmarks_destroy_by_fkeys

  get "users/index"

  resources :notifications do
    put "batch", on: :collection
  end

  devise_for :users, controllers: {invitations: "devise/invitations"}, skip: [:registrations]
  as :user do
    get "/sign_in" => "devise/sessions#new" # custom path to login/sign_in
    get "/sign_up" => "devise/registrations#new", :as => "new_user_registration" # custom path to sign_up/registration
    get "users/edit" => "devise/registrations#edit", :as => "edit_user_registration"
    put "users" => "devise/registrations#update", :as => "user_registration"
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root to: "documents#index"

  # public-facing routes
  resources :documents do
    get "versions"

    resources :document_accesses, path: "access" do
      collection do
        get "import"
        post "import"

        get "destroy_all"
        post "destroy_all"
      end
    end

    resources :document_downloads, path: "downloads" do
      collection do
        get "import"
        post "import"

        get "destroy_all"
        post "destroy_all"
      end
    end

    resources :document_assets, path: "assets" do
      collection do
        get "display_attach_form"
        post "attach_files"

        get "destroy_all"
        post "destroy_all"
      end
    end

    collection do
      get "fetch"
    end
  end

  resources :document_accesses, path: "access" do
    collection do
      get "import"
      post "import"

      get "destroy_all"
      post "destroy_all"
    end
  end

  resources :document_downloads, path: "downloads" do
    collection do
      get "import"
      post "import"

      get "destroy_all"
      post "destroy_all"
    end
  end

  resources :document_assets, path: "assets" do
    collection do
      get "display_attach_form"
      post "attach_files"

      get "destroy_all"
      post "destroy_all"
    end
  end

  get "/documents/:id/ingest", to: "document_assets#display_attach_form", as: "asset_ingest"
  post "/documents/:id/ingest", to: "document_assets#attach_files"
  mount Kithe::AssetUploader.upload_endpoint(:cache) => "/direct_upload", :as => :direct_app_upload

  resources :collections, except: [:show]

  # Note "assets" is Rails reserved word for routing, oops. So we use
  # asset_files.
  resources :assets, path: "asset_files", except: [:new, :create] do
    member do
      put "convert_to_child_work"
    end
  end

  mount Qa::Engine => "/authorities"
  mount ActionCable.server => "/cable"

  authenticate :user, ->(user) { user } do
    mount Blazer::Engine, at: "blazer"
  end
end

app/models/document/bbox_validator.rb
# frozen_string_literal: true

# Bbox Validation
#
# ex. Bad X value
# -100096.7909 is not in boundary
# Rect(minX=-180.0,maxX=180.0,minY=-90.0,maxY=90.0)
# input: ENVELOPE(-100096.7909,-90.0574,43.9474,39.9655)
class Document
  # BboxValidator
  class BboxValidator < ActiveModel::Validator
    def validate(record)
      # Assume true for empty values
      valid_geom = true

      # Sane for W,S,E,N?
      proper_bounding_box(record, valid_geom) unless record.send(Geomg::Schema.instance.solr_fields[:bounding_box]).nil?

      valid_geom
    end

    def proper_bounding_box(record, valid_geom)
      # Min/Max
      min_max = [-180.0, -90.0, 180.0, 90.0]

      # "W,S,E,N" to [W,S,E,N]
      unless record.send(Geomg::Schema.instance.solr_fields[:bounding_box]).split(",").nil?
        geom = record.send(Geomg::Schema.instance.solr_fields[:bounding_box]).split(",")

        if geom.empty?
          valid_geom = true
        elsif geom.size != 4
          valid_geom = false
          record.errors.add(Geomg::Schema.instance.solr_fields[:bounding_box], "invalid W,S,E,N syntax")
        # W
        elsif geom[0].to_f < min_max[0]
          valid_geom = false
          record.errors.add(Geomg::Schema.instance.solr_fields[:bounding_box], "invalid minX present")
        # S
        elsif geom[1].to_f < min_max[1]
          valid_geom = false
          record.errors.add(Geomg::Schema.instance.solr_fields[:bounding_box], "invalid minY present")
        # E
        elsif geom[2].to_f > min_max[2]
          valid_geom = false
          record.errors.add(Geomg::Schema.instance.solr_fields[:bounding_box], "invalid maX present")
        # N
        elsif geom[3].to_f > min_max[3]
          valid_geom = false
          record.errors.add(Geomg::Schema.instance.solr_fields[:bounding_box], "invalid maxY present")
        # Solr - maxY must be >= minY
        elsif geom[1].to_f >= geom[3].to_f
          valid_geom = false
          record.errors.add(Geomg::Schema.instance.solr_fields[:bounding_box], "maxY must be >= minY")
        end

        # Reject ENVELOPE(-118.00.0000,-88.00.0000,51.00.0000,42.00.0000
        # - Double period float-ish things?
        geom.each do |val|
          if val.count(".") >= 2
            valid_geom = false
            record.errors.add(Geomg::Schema.instance.solr_fields[:bounding_box], "invalid ENVELOPE(W,E,N,S) syntax - found multiple periods in a coordinate value.")
          end
        end
      end

      valid_geom
    end
  end
end

app/models/document/controlled_lists.rb
# frozen_string_literal: true

# Constants for various controlled lists for Document attributes.
#
# _Removing_ values from here may require data migration in your existing db.
#
# ## Display lables via i18n
# These are the values actually stored in the DB. Display-translated values can be
# provided via a poorly documented built-in feature of Rails i18n.
#
# If you put an I18n value in your locale file (eg config/locales/en.yml) at:
#     activerecord:
#       attributes:
#         work/format:
#           image: "Really great image"
#
# Then you can look it up with Work.human_attribute_name("format.image"). It even
# does some superclass lookup for you if you have an inheritance hieararchy.
#
# ## Some lists elsewhere
# Controlled values for specific sub-model classes (like Creator) can be found
# within them, not here. This is only for primitive attributes on Work. (But should
# we move sub-model lists here too?)
class Document
  class ControlledLists
    PUBLICATION_STATE = %w[draft published unpublished].freeze

    ACCESS_RIGHTS = %w[Public Restricted].freeze

    LAYER_GEOM_TYPES = %w[Point Line Polygon Image Raster Mixed Table Vector].freeze

    B1G_STATUS = %w[Active Inactive Unknown].freeze

    ACCRUAL_PERIODICITY = [
      "Annual",
      "Semiannual",
      "Quarterly",
      "Monthly",
      "Irregular",
      "As Needed",
      "Once",
      "Never"
    ].freeze

    RESOURCE_CLASS = [
      "Maps",
      "Datasets",
      "Imagery",
      "Collections",
      "Websites",
      "Web services",
      "Other"
    ].freeze

    SCHEMA_PROVIDER = [
      "Indiana University",
      "University of Illinois Urbana-Champaign",
      "University of Iowa",
      "University of Maryland",
      "University of Minnesota",
      "Michigan State University",
      "University of Michigan",
      "Pennsylvania State University",
      "Purdue University",
      "University of Wisconsin - Madison",
      "The Ohio State University",
      "University of Chicago",
      "University of Nebraska-Lincoln"
    ].freeze

    THEME = [
      "Agriculture",
      "Biology",
      "Boundaries",
      "Climate",
      "Economy",
      "Elevation",
      "Environment",
      "Events",
      "Geology",
      "Health",
      "Imagery",
      "Inland waters",
      "Land cover",
      "Location",
      "Military",
      "Oceans",
      "Property",
      "Society",
      "Structure",
      "Transportation",
      "Utilities"
    ].freeze

    TYPE = [
      "Image",
      "Dataset",
      "Service",
      "Interactive Resource",
      "Physical Object",
      "Collection"
    ].freeze
  end
end

app/controllers/documents_controller.rb
# frozen_string_literal: true

# DocumentsController
class DocumentsController < ApplicationController
  ActionController::Parameters.permit_all_parameters = true
  before_action :set_document,
    only: %i[show edit update destroy versions]

  # GET /documents
  # GET /documents.json
  def index
    query_params = {
      q: params["q"],
      f: params["f"],
      page: params["page"],
      rows: params["rows"] || 20,
      sort: params["sort"] || "score desc",
      daterange: params["daterange"] || nil
    }
    @documents = BlacklightApi.new(**query_params)

    respond_to do |format|
      format.html { render :index }
      format.json { render json: @documents.results.to_json }

      # JSON - BTAA Aardvark
      format.json_btaa_aardvark do
        ExportJsonJob.perform_later(current_user, query_params.merge!({format: "json_btaa_aardvark"}), ExportJsonService)
        head :no_content
      end

      # JSON - GBL Aardvark
      format.json_aardvark do
        ExportJsonJob.perform_later(current_user, query_params.merge!({format: "json_aardvark"}), ExportJsonService)
        head :no_content
      end

      # JSON - GBL v1
      format.json_gbl_v1 do
        ExportJsonJob.perform_later(current_user, query_params.merge!({format: "json_gbl_v1"}), ExportJsonService)
        head :no_content
      end

      # CSV - B1G
      format.csv do
        ExportJob.perform_later(current_user, query_params, ExportCsvService)
        head :no_content
      end

      # CSV Document Downloads - B1G
      format.csv_document_downloads do
        ExportJob.perform_later(current_user, query_params, ExportCsvDocumentDownloadsService)
        head :no_content
      end

      # CSV Document Access Links - B1G
      format.csv_document_access_links do
        ExportJob.perform_later(current_user, query_params, ExportCsvDocumentAccessLinksService)
        head :no_content
      end
    end
  end

  # Fetch documents from array of friendlier_ids
  def fetch
    @documents = Document.where(friendlier_id: params["ids"])

    respond_to do |format|
      format.html { render :index }
      format.json { render json: @documents.to_json }

      # JSON - BTAA Aardvark
      format.json_btaa_aardvark do
        ExportJsonJob.perform_later(current_user, {ids: @documents.pluck(:friendlier_id), format: "json_btaa_aardvark"},
          ExportJsonService)
        head :no_content
      end

      # JSON - GBL Aardvark
      format.json_aardvark do
        ExportJsonJob.perform_later(current_user, {ids: @documents.pluck(:friendlier_id), format: "json_aardvark"}, ExportJsonService)
        head :no_content
      end

      # JSON - GBL v1
      format.json_gbl_v1 do
        ExportJsonJob.perform_later(current_user, {ids: @documents.pluck(:friendlier_id), format: "json_gbl_v1"}, ExportJsonService)
        head :no_content
      end

      # CSV - B1G
      format.csv do
        ExportJob.perform_later(current_user, {ids: @documents.pluck(:friendlier_id), format: "csv"}, ExportCsvService)
        head :no_content
      end

      # CSV Document Downloads - B1G
      format.csv_document_downloads do
        ExportJob.perform_later(current_user, {ids: @documents.pluck(:friendlier_id), format: "csv_document_downloads"}, ExportCsvDocumentDownloadsService)
        head :no_content
      end

      # CSV Document Downloads - B1G
      format.csv_document_access_links do
        ExportJob.perform_later(current_user, {ids: @documents.pluck(:friendlier_id), format: "csv_document_access_links"}, ExportCsvDocumentAccessLinksService)
        head :no_content
      end
    end
  end

  # GET /documents/new
  def new
    @document = Document.new
    render :edit
  end

  # GET /documents/1/edit
  def edit
  end

  # GET /documents/1/versions
  def versions
  end

  # POST /documents
  # POST /documents.json
  def create
    @document = Document.new(document_params)
    @document.friendlier_id = @document.send(Geomg::Schema.instance.solr_fields[:id])
    respond_to do |format|
      if @document.save
        format.html { redirect_to documents_path, notice: "Document was successfully created." }
        format.json { render :show, status: :created, location: @document }
      else
        format.html { render :edit }
        format.json { render json: @document.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /documents/1
  # PATCH/PUT /documents/1.json
  def update
    respond_to do |format|
      if @document.update(document_params)
        format.html { redirect_to edit_document_path(@document), notice: "Document was successfully updated." }
        format.json { render :show, status: :ok, location: @document }
      else
        format.html { render :edit }
        format.json { render json: @document.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /documents/1
  # DELETE /documents/1.json
  def destroy
    @document.destroy
    respond_to do |format|
      format.html { redirect_to documents_url, notice: "Document '#{@document.title}' was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def show
    respond_to do |format|
      format.html { redirect_to edit_document_url(@document) }
      format.json { render json: @document.to_json } # App-style JSON
      format.json_aardvark
      format.json_btaa_aardvark
      format.json_gbl_v1
      # B1G CSV
      format.csv { send_data collect_csv([@document]), filename: "documents-#{Time.zone.today}.csv" }

      # @TODO:
      # geoblacklight_version: 1.0 (strict)
      # geoblacklight_version: 1.0 + B1G customizations
      # geoblacklight_version: 2.0 (strict)
      # geoblacklight_version: 2.0 + B1G customizations
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_document
    @document = Document.includes(:leaf_representative).find_by!(friendlier_id: params[:id] || params[:document_id])
  end

  # only allow whitelisted params through (TODO, we're allowing all document params!)
  # Plus sanitization or any other mutation.
  #
  # This could be done in a form object or otherwise abstracted, but this is good
  # enough for now.
  def permittable_params
    %i[title publication_state layer_geom_type_s dct_references_s q f page sort rows daterange]
  end

  def document_params
    Kithe::Parameters.new(params).require(:document).permit_attr_json(Document).permit(permittable_params)
  end

  def collect_csv(documents)
    CSV.generate(headers: true) do |csv|
      csv << Geomg::Schema.instance.exportable_fields.map { |k, _v| k.to_s }
      if documents.instance_of?(BlacklightApi)
        documents.load_all.map do |doc|
          csv << doc.to_csv if doc.present?
        end
      else
        documents.each do |doc|
          csv << doc.to_csv
        end
      end
    end
  end
end

app/helpers/document_helper.rb
# frozen_string_literal: true

# DocumentHelper
module DocumentHelper
  def publication_state_badge(document)
    case document.publication_state
    when "draft"
      link_to("#document_publication_state") do
        tag.span("Draft", class: "badge badge-secondary")
      end
    when "published"
      link_to("#document_publication_state") do
        tag.span("Published", class: "badge badge-success")
      end
    when "unpublished"
      link_to("#document_publication_state") do
        tag.span("Unpublished", class: "badge badge-danger")
      end
    end
  end

  def localize_link(link)
    uri = URI.parse(link)
    "/documents?#{uri.query}"
  end

  def sort_link(link)
    link_to link["attributes"]["label"], localize_link(link["links"]["self"]), {class: "dropdown-item"}
  end

  def link_from_api(link)
    # Append facet - Full URI returned
    uri = URI.parse(link["links"]["self"])
    {action: "add", link: "/documents?#{uri.query}"}
  rescue
    # Remove facet - Only path and query returned
    uri = URI.parse(link["links"]["remove"])
    {action: "remove", link: "/documents?#{uri.query}"}
  end

  def previous_link(links)
    if links["prev"]
      link_to "Previous", localize_link(links["prev"]), {class: "btn btn-outline-primary btn-sm"}
    else
      link_to "Previous", "javascript:;", {class: "btn btn-outline-primary btn-sm disabled", "aria-disabled": true}
    end
  end

  def next_link(links)
    if links["next"]
      link_to "Next", localize_link(links["next"]), {class: "btn btn-outline-primary btn-sm"}
    else
      link_to "Next", "javascript:;", {class: "btn btn-outline-primary btn-sm disabled", "aria-disabled": true}
    end
  end

  def blacklight_link(document)
    "#{BLACKLIGHT_URL}/catalog/#{document.friendlier_id}"
  end
end

app/views/documents/_document_fields.html.erb
<h2 id="identification">Identification</h2>

<div class="grouping">
  <h3 id="descriptive">Descriptive</h3>
  <%= f.input :title, hint: "Theme: city, state, temporal coverage" %>
  <%= f.repeatable_attr_input GEOMG.FIELDS.ALT_TITLE, build: :at_least_one %>

  <%= f.repeatable_attr_input(GEOMG.FIELDS.DESCRIPTION, build: :at_least_one) do |input_name, value| %>
     <div class="form-group">
       <%= f.input_field GEOMG.FIELDS.DESCRIPTION, name: input_name, value: value, as: :text, class: "form-control", rows: 4 %>
     </div>
   <% end %>

  <%= f.repeatable_attr_input GEOMG.FIELDS.DISPLAY_NOTE, build: :at_least_one %>

  <%= f.repeatable_attr_input GEOMG.FIELDS.LANGUAGE, build: :at_least_one,
  html_attributes: { "data-scihist-qa-autocomplete" => qa_search_vocab_path("local", "languages")} %>
</div>

<div class="grouping">
  <h3 id="credits">Credits</h3>
  <%= f.repeatable_attr_input GEOMG.FIELDS.CREATOR, build: :at_least_one %>
  <%= f.repeatable_attr_input GEOMG.FIELDS.B1G_CREATOR_ID, build: :at_least_one %>
  <%= f.repeatable_attr_input GEOMG.FIELDS.PUBLISHER, build: :at_least_one %>

  <%= f.input GEOMG.FIELDS.PROVENANCE, label: "Provider" %>
</div>

<div class="grouping">
  <h3 id="categories">Categories</h3>
  <%= f.repeatable_attr_input GEOMG.FIELDS.B1G_GENRE, build: :at_least_one do |input_name, value| %>
    <%= f.input_field GEOMG.FIELDS.B1G_GENRE, selected: value, include_blank: true, id: nil,
        collection: Document::ControlledLists::GENRE,
        name: input_name,
        class: "form-control input-primitive" %>
  <% end %>
  <%= f.repeatable_attr_input GEOMG.FIELDS.LAYER_GEOM_TYPE, build: :at_least_one,
  html_attributes: { "data-scihist-qa-autocomplete" => qa_search_vocab_path("local", "resource_type")} %>
  <%= f.repeatable_attr_input GEOMG.FIELDS.SUBJECT, build: :at_least_one %>
  <%= f.repeatable_attr_input GEOMG.FIELDS.THEME, build: :at_least_one do |input_name, value| %>
    <%= f.input_field GEOMG.FIELDS.THEME, selected: value, include_blank: true, id: nil,
        collection: Document::ControlledLists::THEME,
        name: input_name,
        class: "form-control input-primitive" %>
  <% end %>
  <%= f.repeatable_attr_input GEOMG.FIELDS.B1G_KEYWORD, build: :at_least_one %>
</div>

<div class="grouping">
  <h3 id="temporal">Temporal</h3>
  <%= f.repeatable_attr_input GEOMG.FIELDS.TEMPORAL, build: :at_least_one %>
  <%= f.input GEOMG.FIELDS.ISSUED, label: "Date Issued", hint: "YYYY", input_html: { data: {js: 'datepicker-years'} } %>
  <%= f.repeatable_attr_input GEOMG.FIELDS.B1G_DATE_RANGE, build: :at_least_one,
  html_attributes: { "data-inputmask-regex" => "'mask': '/\d{4}|\*-\d{4}|\*/'", 'placeholder': 'YYYY-YYYY'} %>
</div>

<div class="grouping">
  <h3 id="spatial">Spatial</h3>
  <%= f.repeatable_attr_input GEOMG.FIELDS.SPATIAL, build: :at_least_one %>
  <%= f.input GEOMG.FIELDS.BBOX, label: "Bounding Box", hint: "W,S,E,N - A centroid will be derived from this value." %>
  <%= f.input GEOMG.FIELDS.GEOM, label: "Geometry", hint: "WKT - An ENVELOPE, POLYGON, or MULTIPOLYGON value. Use ENVELOPE(-180,180,90,-90) for a whole earth geometry." %>
  <%= f.repeatable_attr_input GEOMG.FIELDS.B1G_GEONAMES, build: :at_least_one %>
</div>

<div class="grouping">
  <h3 id="relations">Relations</h3>
  <%= f.repeatable_attr_input GEOMG.FIELDS.RELATION, build: :at_least_one %>
  <%= f.repeatable_attr_input GEOMG.FIELDS.MEMBER_OF, build: :at_least_one %>
  <%= f.repeatable_attr_input GEOMG.FIELDS.IS_PART_OF, build: :at_least_one %>
  <%= f.repeatable_attr_input GEOMG.FIELDS.SOURCE, build: :at_least_one %>
  <%= f.repeatable_attr_input GEOMG.FIELDS.IS_VERSION_OF, build: :at_least_one %>
  <%= f.repeatable_attr_input GEOMG.FIELDS.REPLACES, build: :at_least_one %>
  <%= f.repeatable_attr_input GEOMG.FIELDS.IS_REPLACED_BY, build: :at_least_one %>
</div>

<h2 id="distribution">Distribution</h2>

<div class="grouping">
  <h3 id="object">Object</h3>
  <%= f.input GEOMG.FIELDS.FORMAT, :input_html => { :data => { "scihist-qa-autocomplete" => qa_search_vocab_path("local", "formats")}}, label: "Format" %>
  <%= f.input GEOMG.FIELDS.FILE_SIZE %>
  <%= f.input GEOMG.FIELDS.LAYER_ID %>
  <%= f.input GEOMG.FIELDS.GEOREFERENCED, as: :boolean, inline_label: 'Georeferenced' %>
</div>

<div class="grouping">
  <h3 id="links">Links</h3>
  <%= f.repeatable_attr_input(GEOMG.FIELDS.REFERENCES, build: :at_least_one) do |sub_form| %>
    <%= category_and_value(sub_form, category_list: Document::Reference::REFERENCE_VALUES.keys) %>
  <% end %>
  <%= f.input GEOMG.FIELDS.B1G_IMAGE, label: "B1G Image URL" %>

  <%- if @document.persisted? %>
    <h3 id="multiple-download-links"><%= link_to "Multiple Download Links", document_document_downloads_url(@document) %></h3>
    <div class="table-responsive">
      <table class="table table-striped table-bordered">
        <thead>
          <tr>
            <th colspan="2">Actions</th>
            <th>Layer Slug</th>
            <th>Download Label</th>
            <th>Download URL</th>
          </tr>
        </thead>

        <tbody>
          <% @document.document_downloads.each do |document_download| %>
            <tr>
              <td><%= link_to 'Edit', edit_document_document_download_path(document_download.document, document_download) %></td>
              <td><%= link_to 'Destroy', document_document_download_path(document_download.document, document_download), method: :delete, data: { confirm: 'Are you sure?' } %></td>
              <td><%= link_to document_download.friendlier_id, document_path(document_download.document) %></td>
              <td><%= document_download.label %></td>
              <td><%= link_to document_download.value %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  <% end %>

</div>

<h2 id="administrative">Administrative</h2>
<div class="grouping">
  <h3 id="codes">Codes</h3>

  <% if @document.persisted? %>
    <%= f.input GEOMG.FIELDS.LAYER_SLUG, required: true, label: "ID", input_html: { disabled: true } %>
  <% else %>
    <%= f.input GEOMG.FIELDS.LAYER_SLUG, required: true, label: "ID" %>
  <% end %>

  <%= f.repeatable_attr_input GEOMG.FIELDS.IDENTIFIER, build: :at_least_one %>
  <%= f.input GEOMG.FIELDS.B1G_CODE, label: "Code" %>
</div>

<div class="grouping">
  <h3 id="rights">Rights</h3>
  <%= f.input GEOMG.FIELDS.ACCESS_RIGHTS, collection: Document::ControlledLists::ACCESS_RIGHTS, required: true %>
  <%= f.repeatable_attr_input GEOMG.FIELDS.RIGHTS_HOLDER, build: :at_least_one %>
  <%= f.repeatable_attr_input GEOMG.FIELDS.LICENSE, build: :at_least_one %>
  <%= f.repeatable_attr_input GEOMG.FIELDS.RIGHTS, build: :at_least_one %>
</div>

<div class="grouping">
  <h3 id="life-cycle">Life Cycle</h3>

  <% if @document.persisted? %>
    <%= f.input :created_at, as: 'string', label: "Created At", input_html: { disabled: true } %>
    <%= f.input :updated_at, as: 'string', label: "Last Updated", input_html: { disabled: true } %>
  <% end %>

  <%= f.input GEOMG.FIELDS.B1G_ACCRUAL_METHOD, label: "Accrual Method" %>
  <%= f.input GEOMG.FIELDS.B1G_ACCRUAL_PERIODICITY, collection: Document::ControlledLists::B1G_ACCRUAL_PERIODICITY, label: "Accrual Periodicity" %>
  <%= f.repeatable_attr_input GEOMG.FIELDS.B1G_DATE_ACCESSIONED, build: :at_least_one %>
  <%= f.input GEOMG.FIELDS.B1G_DATE_RETIRED, label: 'Date Retired', hint: 'YYYY-MM-DD', input_html: { data: {js: :datepicker} } %>
  <%= f.input GEOMG.FIELDS.B1G_STATUS, label: 'Status' %>

  <% if @document.persisted? %>
    <%= f.input :publication_state, label: 'Publication State', required: true, collection: Document::ControlledLists::PUBLICATION_STATE %>
  <% else %>
    <%= f.hidden_field :publication_state %>
  <% end %>
</div>

<div class="grouping">
  <h3 id="accessibility">Accessibility</h3>
  <%= f.input GEOMG.FIELDS.SUPPRESSED, as: :boolean, inline_label: 'Suppressed' %>
  <%= f.input GEOMG.FIELDS.B1G_CHILD_RECORD, as: :boolean, inline_label: 'Child' %>
  <%= f.repeatable_attr_input GEOMG.FIELDS.B1G_MEDIATOR, build: :at_least_one %>
  <%= f.input GEOMG.FIELDS.B1G_ACCESS %>
</div>
<hr/>

app/views/documents/_form_group.html.erb
<h3 id="<%= form_element.label.parameterize %>" class="grouping"><%= form_element.label %></h3>

app/views/documents/_form_header.html.erb
<h2 id="<%= form_element.label.parameterize %>"><%= form_element.label %></h2>

app/views/documents/_form_nav.html.erb
<div class="make-me-sticky mt-4 ml-4">
  <nav class="nav flex-column ml-4 mt-6">
    <strong class="mt-4"><%= link_to "View in Geoportal", blacklight_link(@document), { class: 'mt-6', target: :_blank } %></strong>

    <%- form_elements = FormElement.all.order(position: :asc) %>
    <%- form_elements.each do |form_element| %>
      <% if form_element.kind_of? FormHeader %>
        <strong class="mt-2"><a data-controller="scroll-to" class="mt-4" href="#<%= form_element.label.parameterize(separator: '-') %>"><%= form_element.label %></a></strong>
      <% end %>
      <% if form_element.kind_of? FormGroup %>
        <a data-controller="scroll-to" class="ml-2" href="#<%= form_element.label.parameterize(separator: '-') %>"><%= form_element.label %></a>
      <% end %>
    <% end %>

    <% if @document.persisted? %>
      <%= link_to "Institutional Access Links", document_document_accesses_url(@document), class: "ml-2" %>
      <%= link_to "Multiple Download Links", document_document_downloads_url(@document), class: "ml-2" %>
      <%= link_to "Additional Assets", document_document_assets_url(@document), class: "ml-2" %>
    <% end %>
  </nav>
</div>